SELECT PACKAGE_SEQ,P.TRANSMISSION_SEQ,PKG_ID,FXG_SVC_CD,FXG_HUB_CD,DEST_PSTL_CD,CHANL_APP_ID,MAILER_ID,PACKAGING_TYP,
	   PERISHABLE_FLAG,DANGD_CD,DISPOSITION_FLAG,PKG_VLD_FLAG,BLOCK_SHPMT_FLAG,DEL_CONF_REQD_FLAG,WGT_SRC_CD,
	   DIM_SRC_CD,PKG_WGT,PKG_WIDTH,PKG_LENGTH,PKG_HEIGHT,PKG_WGT_UOM_CD,PKG_DIM_UOM_CD,MAIL_CLASS_CD,
	   MAIL_SUB_CLASS_CD,PRCS_SIZE_CD,PRCS_CAT_CD,PSTL_CD_TYP,INVOICE_NUM,PO_NUM,RMA_NUM,METER_NUM,PAYOR_TYP,
	   RETURN_TYP,LABEL_FMT,HASH_VALUE,CREATED_DT,CREATED_BY,UPDATED_DT,UPDATED_BY,FCL_UUID_NM,FXG_MBR_NM,EVNT_UUID_NM,
	   UNVSL_PKG_NBR,FEDEX_CUST_ACCT_NBR,SP_CUST_ID,DIST_CTR_ID,DIST_CTR_CNTRY_CD,CUST_MFST_ID,MFST_ID,MFST_GRP_TXT,
       XMT_VLD_FLAG,XMT_CMPLT_FLAG,MESSAGE_HEADER_ID,PKG_CNT,XMT_BOL,SHIP_DT,EXP_ARR_DT,SHP_SFTWR_SYST,SHP_SFTWR_VERS,
       SHP_SFTWR_VEND,TEST_ONLY_FLAG,XMT_DT,XMT_FMT_VERS,XML_GEN_SRC,FXG_XMT_ID
JOIN SPCT_SCHEMA.TRANSMISSION T ON T.TRANSMISSION_SEQ = P.TRANSMISSION_SEQ
FROM SPCT_SCHEMA.PACKAGE P WHERE PKG_ID IN (:packageIds)